title: Milán Mondok
logo: /assets/img/mondok.jpg
description: Computer engineer
website1: https://ftsrg.mit.bme.hu
affiliation1: Critical Systems Research Group
title1: PhD Student
scholar: NiiJFdgAAAAJ
mail: mondok@mit.bme.hu
linkedin: milanmondok
theme: jekyll-theme-minimal
